// Code generated by @apexlang/codegen. DO NOT EDIT.

package greeter

import (
	"context"
)

type ns struct{}

func (n *ns) Namespace() string {
	return "greeting.v1"
}

type Greeter interface {
	SayHello(ctx context.Context, firstName string, lastName string) (string, error)
}
