// Code generated by @apexlang/codegen. DO NOT EDIT.

package greeter

import (
	"context"

	"github.com/wapc/tinygo-msgpack"
	"github.com/wapc/tinygo-msgpack/convert"
	"github.com/wapc/wapc-guest-tinygo"
)

var _ = convert.Package

func RegisterGreeter(svc Greeter) {
	wapc.RegisterFunction("greeting.v1.Greeter/sayHello", greeterSayHelloWrapper(svc))
}

func greeterSayHelloWrapper(svc Greeter) wapc.Function {
	return func(payload []byte) ([]byte, error) {
		ctx := context.Background()
		decoder := msgpack.NewDecoder(payload)
		var inputArgs greeterSayHelloArgs
		inputArgs.Decode(&decoder)
		response, err := svc.SayHello(ctx, inputArgs.FirstName, inputArgs.LastName)
		if err != nil {
			return nil, err
		}
		var sizer msgpack.Sizer
		sizer.WriteString(response)
		ua := make([]byte, sizer.Len())
		encoder := msgpack.NewEncoder(ua)
		encoder.WriteString(response)
		return ua, nil
	}
}
